### ISSUE TITLE
Display programme statistics on home page

### ISSUE THREAD

**Issue by chrisala** [AtlasOfLivingAustralia/fieldcapture#299]
- 6 displayed at a time with random selection from a known list.
- Each score has a custom label, colour and image.
- Support for "show more" (Displays different stats or just another random selection?)

**Comment by chrisala** [comment]
The stats to display are:

# Threatened Species Strategy:
*  number of projects addressing threatened species
 
# Reef
* Total number of farming entities adopting changed management practices
* Weight of marine debris removed
* (Pest Management) Number of Crown of Thorn Starfish removed
* Length of fences erected 
 
# Additional info-graphics for Future projects (Reef Trust phase II, III and IV)
* Total Erosion area treated

# Indigenous
* No employed and no of on country visits for Indigenous

# National Landcare Programme
*  $XXX and no. Project Sustainable ag -  If we tell you which budget line is sustainable agriculture could we aggregate this figure? 
*  $XXX and no. Projects - to support Indigenous projects (using Asset addressed)
*  $XXX and no. Projects - that help protect threatened species and their habitat (using Asset addressed)
*  $XXX and no. Projects - that support the health of World Heritage Area (using Asset addressed).
*  Pest animals area managed – target for now, moving to delivered down the track?
*  Weeds treated by area, moving to delivered down the track?
*    20MT-number of trees (>2m) planted, also ability to modify this to number of trees surviving as program matures.  Display – progress against target of 20 million
 
# All programmes:
* Ha of weeds removed
* All programmes: Area treated for felius catus

# NLP:  
* Ha weed treatment by main activity partner ‘Local Landcare, ‘Friends of’, community, or farmer groups
* NLP: No of volunteers participating in project activities
 
# Green Army: 
 * No. of Participants who commenced projects
 * Green Army: No of teams (projects), active and complete

**Comment by chrisala** [comment]
Andy, can you please check the list of stats as well as the sources for each one?

**Comment by AndyWestcott** [comment]
Hi Chris, list below of the stat heading, OK indicates checked the logic and agree, otherwise have left comment on changes needed.
Threatened Species Strategy: Ok
Reef: This should be the Reef Trust programme-email sent to line area 21/10 to confirm. They are reviewing all these questions.
Indigenous: Ok
NLP: 
$XXX and no. Project Sustainable ag - If we tell you which budget line is sustainable agriculture could we aggregate this figure? 
-Ag outcome is "Farmers and fishers are increasing their long term returns through better management of the natural resource base"

• $XXX and no. Projects - to support Indigenous projects (using Asset addressed)
-Ok

 • $XXX and no. Projects - that help protect threatened species and their habitat (using Asset addressed)
-Ok

 • $XXX and no. Projects - that support the health of World Heritage Area (using Asset addressed).
-Ok

 • Pest animals area managed – target for now, moving to delivered down the track?
Target for now.

 • Weeds treated by area, moving to delivered down the track?
AS above, target for now

 • 20MT-number of trees (>2m) planted, also ability to modify this to number of trees surviving as program matures. Display – progress against target of 20 million

To begin with make it: the combined target for "Total No. of plants surviving with mature height > 2 metres". Field to be called "Number of trees contracted for planting", moving to number planted, then eventaully number established as the data becomes available.

All programmes: OK, what do the numer look like for the CAT area?
NLP: OK
Green Army: These need to be scrapped as they wont be in MERIT anymore, just want the environmental stuff from the current mock up. Will confrim with Amy, email sent 21/10

**Comment by chrisala** [comment]
More questions: 
1. which asset addressed should be used for: 'to support Indigenous projects'?
2. which asset addressed should be used for: ' that help protect threatened species and their habitat'?

**Comment by AndyWestcott** [comment]
$XXX and no. Projects - to support Indigenous projects (using Asset addressed):
-Indigenous Cultural Values; and
-indigenous ecological knowledge

 • $XXX and no. Projects - that help protect threatened species and their habitat (using Asset addressed)
-Threatened Species, lets modify wording to "Projects - that help protect threatened species"

**Comment by AndyWestcott** [comment]
hi Chris, commetns from reef trust:

Reef
-Total number of farming entities adopting changed management practices [Source:value of the score "Total No. of farming entities adopting sustainable practice change" for projects in the "Reef Rescue 2013/14" sub-programme. (Using Reef Trust gives a value of 0 for this score)] 
ANDY: Assume this should be pointed at Reef Trust programmes not Reef Rescue, do you expect this score of 0 to improve? 
REEF: Can this be both? If not, preference is Reef Rescue (for now). 
• Weight of marine debris removed [Source: value of the score "Weight of debris removed (Tonnes)" for projects in the "Reef Rescue 2013/14" sub-programme. Can this be assumed to be marine debris? Using Reef Trust gives a value of 0 for this score]-Also as Reef Trust has on farm actions can we assume debris removal reported in that stream is entirely marine? 
REEF: This is Reef Trust only – marine debris project is under Reef Trust phase 1. Results should be more than 0 once the current report is approved. 
• (Pest Management) Number of Crown of Thorn Starfish removed [Source: value of the "Total No. of individuals or colonies of pest animals destroyed" score where species is "Acanthaster planci".] Do we need to have this look for any other wording? Are all recipients using scientific name? Can this be defined in the info graphic? 
REEF: I’m sure the recipients are using the scientific name. Preference would be the ‘area covered by targeted COTS removal as its about protecting the reef, not removing COTS. 
• Length of fences erected [Source value of the "Total length of fence (Km)" where the sub-programme is "Reef Rescue 2013/14"] 
REEF: Should this be just Reef Trust Can this be both? If not, preference is Reef Rescue (for now).

**Comment by AndyWestcott** [comment]
Hi Chirs, just noticed the green army comment in my post of 22 days ago. definetly just the environmental stats for them. Do you have a list for those? We are just about through the wording changes on the current infographics.

**Comment by chrisala** [comment]
Hi Andy, the only green army stats I have were the project related ones.

**Comment by chrisala** [comment]
Changes have been made and are in dev. Green Army Environmental stats are outstanding.

**Comment by AndyWestcott** [comment]
great, we noticed that one of the weeds grpahics has no Ha, and no room for it. Sending through slight tweak

**Comment by AndyWestcott** [comment]
Mitch spotted that the alignment is often different when the  title is missing. For all1 and all2 and title "all programmes

**Comment by chrisala** [comment]
Green army stats added, requested changes have been made.  Fixed a couple of stats that were showing 0s.

**Comment by AndyWestcott** [comment]
Looks good chris, for Green army - Ha of weeds treated, can we make Unit = ha and label = managed for weeds. Looking great.

**Comment by chrisala** [comment]
In dev now.
