### ISSUE TITLE
Implement "Point of Interest" selection and display.

### ISSUE THREAD

**Issue by chrisala** [AtlasOfLivingAustralia/fieldcapture#305]
- Random display from *all* projects that have POIs with photos.
- Display as a slideshow / carousel.

**Comment by chrisala** [comment]
Because of privacy issues around uploaded photopoints, we should only be displaying public project photos that have a privacy declaration made.
Random selection from any project.

**Comment by chrisala** [comment]
Hi Andy, please give me feedback on this - it is available in dev.

**Comment by Mitchdoe** [comment]
Hey Chris,

Andy is on leave today and Monday.
Looks good, a couple of questions about the POIs:

1.       Could another criterion be added to the selection, in that only projects ticked as “case study” could be used? Due to the fact that many projects aren’t using POIs correctly and this could provide an easy way to prevent POIs we don’t want from appearing on the home page.

2.       Could we shift the text to sit above each photo rather than over it, and also have the title contain a hyperlink to the project?

Cheers
Mitch

**Comment by chrisala** [comment]
Thanks Mitch.
1: Andy requested that we drop the POI thing because users don't have to make a privacy declaration.  The photos that are displayed all have a privacy declaration made and were requested to be selected from all projects (rather than just promoted ones).
2.  If you click the image, you will go to the project home page although I appreciate that might not be obvious.  I could change the project name to look like a link?  Re: text placement, the readability issue could be improved by putting a transparent background behind the text to up the contrast?

**Comment by Mitchdoe** [comment]
Should have picked up on the link, that should be enough.
So they aren’t all going to be POIs, they are just public project images?
Could be worth trying the transparent background, Giraffe probably have a better idea than me on setting the text though.

**Comment by AndyWestcott** [comment]
Issue 1: That matches what we asked for. Need to flag this with Exec Chris as they may not be happy with some of the images coming up.
Issue2: Project name being a link sounds great. Should we be  working on comments now on the current design in Dev or is Giraffe still activiely changing it?

**Comment by chrisala** [comment]
1. The images being displayed now are exactly representative of what will
happen in production (I did this deliberately to give a strong feel of what
it will be).
2. OK.
Re: comments, personally I think unless things are clearly unfinished (i.e.
not styled at all) bring them on.  The earlier they are raised the earlier
they can be addressed.  If it's still a work in progress it's still useful
to have your thoughts on how you expect it to be.

**Comment by AndyWestcott** [comment]
1: We are going to need the abvility to view then promote images to the carousel. Exec not happy with some of the images showing up. Long term this is going to fall on grant managers to improve the standard. Short term though we need to be able to tick off thats its ok for carousel.

comments: collating this arvo for you

**Comment by chrisala** [comment]
There is an implementation of this in dev now.  Select images using the administration menu -> Home Page Images page.

**Comment by AndyWestcott** [comment]
Looks great, few questions:
 # if we dislike can the image drop off the list?
 # what happens if we dont like or dislike an image? Assume it just reamins an option for later?
 # Once we have liked an image, had it in roatation for a while and want to change the carousel, whats the process? Do we have to dislike it? If yes would that mean it drops off the list? Would be good to keep these for later.

**Comment by chrisala** [comment]
1. Once you dislike, the image will never be selected for the home page.
2. Right now dislike is treated the same as no selection.
3. Yes, process is to dislike the image.  If you want it to be selectable again you have to re-like it.
